- name: Create a jenkins job using basic auth
  jenkins_job:
    config: "{{ lookup('file', 'templates/test.xml') }}"
    name: test
    password: admin
    url: http://172.31.11.170:8080
    user: admin