- name: Create Folders
  jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item.name}}"
    password: admin
    url: http://172.31.11.170:8080
    user: admin
  loop:
    - { name: "ci-pipelines"}

- name: Create a multibranch pipelines
  jenkins_job:
    config: "{{ lookup('file', 'templates/mbranch.xml') }}"
    name: "ci-pipelines/{{item.name}}"
    password: admin
    url: http://172.31.11.170:8080
    user: admin
  loop:
    - { name: "cart"}