- name: Create Folders
  jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item.name}}"
    password: admin
    url: http://172.31.11.170:8080
    user: admin
  loop:
    - { name: "ci-pipelines"}

- name: Include Multibranch task file
  ansible.builtin.include_tasks: mbranch.yml
  loop:
    - { name: "cart"}
    - { name: "catalogue"}
    - { name: "user"}
    - { name: "shipping"}
    - { name: "payment"}
    - { name: "frontend"}
